version: '3'

services:
  backend:
    image: go
    build: .
    ports:
      - "8060:8060"

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - nuxt
  nuxt:
    image: nuxt
    build: ./nuxt-project
    ports:
      - "3000:3000"
    depends_on:
      - backend