version: '3'

services:
  backend:
    image: your-golang-image
    ports:
      - "5000:5000"

  frontend:
    image: your-nuxt-image
    ports:
      - "3000:3000"

  nginx:
    image: your-nginx-image
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
